field: 0c9da4ed-c32a-4005-adb2-8af66b613d8e # Blocks
fieldLayouts:
  46171e49-beee-4231-91d1-fad995dfabe9:
    tabs:
      -
        elements:
          -
            fieldUid: abf5b55d-598e-462f-b045-82a72d9925be # Blockquote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  abf5b55d-598e-462f-b045-82a72d9925be: # Blockquote
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: blockquote
    instructions: ''
    name: Blockquote
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: blockquote
name: Blockquote
sortOrder: 5
