field: 0c9da4ed-c32a-4005-adb2-8af66b613d8e # Blocks
fieldLayouts:
  472c178e-14a5-4dee-b772-57d852c37f7e:
    tabs:
      -
        elements:
          -
            fieldUid: 5bc99274-d138-4da9-9a81-b4ca97e30012 # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5bc99274-d138-4da9-9a81-b4ca97e30012: # Video
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: video
    instructions: ''
    name: Video
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - video
      defaultUploadLocationSource: 'volume:53e09cb7-c7ae-472e-bd5c-2cc7d65dee0e' # Media
      defaultUploadLocationSubpath: video
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:53e09cb7-c7ae-472e-bd5c-2cc7d65dee0e' # Media
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: video
name: Video
sortOrder: 3
