dateModified: 1650709255
email:
  fromEmail: anuar@heyblackmagic.com
  fromName: 'Foundation Site'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0b797197-2780-406a-a3ac-2651f463ac74: Blockquote # Blockquote
    0c9da4ed-c32a-4005-adb2-8af66b613d8e: Blocks # Blocks
    3b53818e-db5e-40fe-a966-f84478128b5d: Text # Text
    4d13e91e-2531-45c9-859c-42674703eac9: Update # Update
    5bc99274-d138-4da9-9a81-b4ca97e30012: Video # Video
    7aceaed4-2bfc-4a10-8283-035b91e2f8c2: Default # Default
    53e09cb7-c7ae-472e-bd5c-2cc7d65dee0e: Media # Media
    85bb94ac-ee0b-44f4-881a-a00190595a35: Code # Code
    89a9bf71-5d7f-41de-9bda-98b30337a1a6: Text # Text
    310cbb9c-a852-47b6-a6a9-ffc29afeab1f: 'Black Magic Docs' # Black Magic Docs
    428f65fe-9958-4654-98a8-5a18cd762f6d: Intro # Intro
    4646b0c5-ae0b-47f7-a53d-f621bd797041: 'Show Update Info' # Show Update Info
    79036237-60bd-4a7a-b558-05776ab2f208: Docs # Docs
    a45d9373-bc4f-4ddd-93ca-d5bfdcd95e9a: Caption # Caption
    abf5b55d-598e-462f-b045-82a72d9925be: Blockquote # Blockquote
    b88f9c1f-f1ff-4f44-a64f-9db2ab43a9bd: Common # Common
    b1772479-93cf-472e-844a-9969f822491c: Video # Video
    be9cd29c-f601-4135-b533-4410093768f2: 'Update note' # Update note
    c3cd35fb-d5dd-487b-84fa-ccc84aecff94: 'Black Magic Docs' # Black Magic Docs
    c932de98-0288-4c4a-8160-b0b80ea4c6a5: 'Open image in a modal?' # Open image in a modal?
    d8abe207-76dd-4308-95f3-b623080169a6: Image # Image
    e9b20bdd-5ca0-48f1-8a6f-08f2cc9fa3ad: Code # Code
    f67e2256-059c-443f-8808-6e34d72084cb: Caption # Caption
    fba99691-a856-4400-8a12-f504c60b3059: Image # Image
plugins:
  cloner:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: 'Black Magic Docs'
  retryDuration: null
  schemaVersion: 3.7.33
  timeZone: America/Mexico_City
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
